name: Sync with another repository

on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 * * * *'  # Запускать каждый час, для проверки обновлений
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch changes from the external repository
        run: |
          git remote add external https://github.com/gSpotx2f/ruantiblock_openwrt
          git fetch external

      - name: Check for updates and sync with the other Git host
        run: |
          commits=$(git log external/master..external/master --oneline | wc -l)
          echo "Number of new commits: $commits"
          if [ "$commits" -gt 0 ]; then
            git remote add gitlab https://github.com/heshgggg/ruantiblock_openwrt
            git push gitlab external/master:refs/heads/master
            git fetch gitlab
            update_number=$(git rev-list --count gitlab/main)
            if [ "$update_number" -ge 5 ]; then
              update_branch="update_$update_number"
              git checkout -b $update_branch
              git push gitlab $update_branch
            fi
          fi
